config/routes.rb
VitaminM::Application.routes.draw do
  resources :bill_types

  resources :bills

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root :to => 'bill_types#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :user

end

app/models/bill_type.rb
class BillType < ActiveRecord::Base
end

app/models/mobile_bill.rb
class MobileBill < Bill
end

app/models/payment_url.rb
class PaymentUrl < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name

  #Associations
  has_many :bills, :through => :bills_users

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
  	data = access_token.info
  	user = User.where(:email => data["email"]).first

  	unless user
  		user = User.create(name: data["name"],
  			email: data["email"],
  			password: Devise.friendly_token[0,20]
  			)
  	end
  	user
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bill_types_controller.rb
class BillTypesController < ApplicationController

   before_filter :authenticate_user!
   
  # GET /bill_types
  # GET /bill_types.json
  def index
    @bill_types = BillType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bill_types }
    end
  end

  # GET /bill_types/1
  # GET /bill_types/1.json
  def show
    @bill_type = BillType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill_type }
    end
  end

  # GET /bill_types/new
  # GET /bill_types/new.json
  def new
    @bill_type = BillType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill_type }
    end
  end

  # GET /bill_types/1/edit
  def edit
    @bill_type = BillType.find(params[:id])
  end

  # POST /bill_types
  # POST /bill_types.json
  def create
    @bill_type = BillType.new(params[:bill_type])

    respond_to do |format|
      if @bill_type.save
        format.html { redirect_to @bill_type, notice: 'Bill type was successfully created.' }
        format.json { render json: @bill_type, status: :created, location: @bill_type }
      else
        format.html { render action: "new" }
        format.json { render json: @bill_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bill_types/1
  # PUT /bill_types/1.json
  def update
    @bill_type = BillType.find(params[:id])

    respond_to do |format|
      if @bill_type.update_attributes(params[:bill_type])
        format.html { redirect_to @bill_type, notice: 'Bill type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_types/1
  # DELETE /bill_types/1.json
  def destroy
    @bill_type = BillType.find(params[:id])
    @bill_type.destroy

    respond_to do |format|
      format.html { redirect_to bill_types_url }
      format.json { head :ok }
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users/omniauth_callbackscontroller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
	
	def inline_error(obj, attr)
		"<span class='error #{attr}'>#{obj.errors[attr].to_sentence}&nbsp;</span>"
	end

	def setup_obj(obj, association)
		obj.send(association.to_s).blank? ? obj.send(association.to_s).build : obj.send(association.to_s)
	end

end

app/helpers/bill_types_helper.rb
module BillTypesHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/bill_types/_form.html.erb
<%= form_for(@bill_type) do |f| %>
  <% if @bill_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_type.errors.count, "error") %> prohibited this bill_type from being saved:</h2>

      <ul>
      <% @bill_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_types/edit.html.erb
<h1>Editing bill_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_type %> |
<%= link_to 'Back', bill_types_path %>

app/views/bill_types/index.html.erb
<div id="bill_types"></div>
<script type="text/javascript">
  $(function() {
    // vitaminM is the app name
    window.router = new VitaminM.Routers.BillTypesRouter({billTypes: <%= @bill_types.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/bill_types/new.html.erb
<h1>New bill_type</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_types_path %>

app/views/bill_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bill_type.name %>
</p>


<%= link_to 'Edit', edit_bill_type_path(@bill_type) %> |
<%= link_to 'Back', bill_types_path %>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<div id="bills"></div>
<script type="text/javascript">
  $(function() {
    // vitaminM is the app name
    window.router = new VitaminM.Routers.BillsRouter({bill_types: <%= @bills.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bill.name %>
</p>

<p>
  <b>Display name:</b>
  <%= @bill.display_name %>
</p>

<p>
  <b>Amount:</b>
  <%= @bill.amount %>
</p>

<p>
  <b>Due date:</b>
  <%= @bill.due_date %>
</p>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>VitaminM</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
		<% if user_signed_in? %>
		Signed in as <%= current_user.email %>.
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>. 
		<% else %>
		<%= link_to "Connect With Google", user_omniauth_authorize_path(:google_oauth2) %>
		<%= link_to "Sign in", '/users/sign_in' %>   
		<%= link_to "Sign up", '/users/sign_up' %>   

		 <% end %>
	</div>


	<%= yield %>

</body>
</html>